### ISSUE TITLE
Rename cmd_entries to cmd

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/ml#263]
How about renaming `cmd_entries` to `cmd`? Would be consistent with the typical Go program structure.

@zurk @EgorBu @r0mainK what do you think?

**Comment by r0mainK** [comment]
but only the subfolder, or also things like: `repos2ids_entry`  or `repos2bow_entry_template` ?

**Comment by vmarkovtsev** [comment]
Only the directory, yes.

**Comment by zurk** [comment]
Let's do it!

**Comment by r0mainK** [comment]
PR for ml: https://github.com/src-d/ml/pull/264
PR for apollo: https://github.com/src-d/apollo/pull/55

**Comment by zurk** [comment]
I think it is time to close it 
@vmarkovtsev

**Comment by vmarkovtsev** [comment]
Thanks
