### ISSUE TITLE
Fix assemble_spark_config that alter default values now

### ISSUE THREAD

**Issue by zurk** [src-d/ml#270]
I found out in tests that `SparkDefault.PACKAGES` and `SparkDefault.CONFIG` were changed. 
To fix it I need to change a behavior of `assemble_spark_config` function.

**Comment by zurk** [comment]
@vmarkovtsev please assign me.

**Comment by r0mainK** [comment]
@zurk  could we actually change `SparkDefault.PACKAGES` to `SparkDefault.JARS` ? because packages could be used to manage python package dependencies that are not on the workers, like we do for `sourced-ml` and `sourced-engine`.

**Comment by zurk** [comment]
I am not sure it is a good idea. It is the same as name variable for python packages as `PY`. And I do not see any conflict in naming here.

If you really what we can choose something like `SparkDefault.JAR_PACKAGES`. It corresponds to `spark.jars.packages` config variable in spark.

**Comment by r0mainK** [comment]
True, there is no naming conflicts (yet), but I think it would be more verbose then simply `package`. Anyway Im all for `SparkDefault.JAR_PACKAGES` we'll just have to port it apollo afterwards

**Comment by zurk** [comment]
Done
