### ISSUE TITLE
Update Spark to 2.3

### ISSUE THREAD

**Issue by r0mainK** [src-d/ml#276]
@vmarkovtsev @zurk 

Just saw [this PR](https://github.com/src-d/engine/pull/403) in engine, I think we should also upgrade when it is merged and stable. I don't think there are many differences in the python's API, so it should not be too much refactoring on our side, and there is some pretty cool new features in 2.2 and 2.3

**Comment by smola** [comment]
Keep in mind that there are no plans to upgrade our clusters to Spark 2.3 yet. So let's not break compatibility with 2.2.

**Comment by vmarkovtsev** [comment]
jgit is deprecated, we are switching to [gitbase-spark-connector](https://github.com/src-d/gitbase-spark-connector).
