### ISSUE TITLE
Add "single-shot" mode to the token parser

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/ml#298]
Our heuristic token parser generates several variants of the split sometimes. E.g.
`wdSize` becomes `["wd", "size", "wdsize"]`.

We need to add an "aggressive" mode which does not generate repetitions and use it to train our neural identifier splitter. Besides, I want the following in this mode:

```
loooong_sh_loooong_sh -> looong, sh, loooong, sh
SmallIdFooo -> small, id, foo
```

**Comment by zurk** [comment]
Yes, because of https://github.com/src-d/ml/pull/204
On my way

**Comment by zurk** [comment]
Addressed. 

Going to fix the dataset.

**Comment by zurk** [comment]
Actually, we can use `split` instead of `process_token` as @warenlg did here: https://github.com/src-d/ml/blob/master/sourced/ml/transformers/content2ids.py#L67 it gives us exactly the same result you want. So, I am not sure this PR is helpful. It just makes things more complicated.

**Comment by vmarkovtsev** [comment]
But wait I see that you've changed the code to not return duplicate tokens. Waren's code suffers from the same problem.

**Comment by zurk** [comment]
Ok. It was a too fast conclusion. But in case you set `min_split_length=1` you will have only independent part of an identifier. Because only small pieces sticks.

**Comment by zurk** [comment]
PR is merged. 
@vmarkovtsev do not forget to close :)
