### ISSUE TITLE
Installing fails with Python 3.7

### ISSUE THREAD

**Issue by zurk** [src-d/ml#318]
Due to the issue https://github.com/snowballstem/pystemmer/issues/18 it is not possible to install current sourced-ml package smoothly via `pip3 install sourced-ml` using python 3.7 if you do not have `cython` package installed.

And it is hard to fix it here because we can not specify installation order in `setup(...)`.
However, putting `Cython` before `PyStemmer` in `requirements.txt` seems to work. So at least you can run
```bash
pip3 install -r requirements.txt
pip3 install .
```
I create a PR with `requirements.txt` update for now. 
When I have time I try to fix the issue in PyStemmer itself. 

A related issue in style-analyzer: https://github.com/src-d/style-analyzer/issues/175.

@vmarkovtsev please assign me.

**Comment by vmarkovtsev** [comment]
This is solved by `setup_requires=["cython"]`

**Comment by zurk** [comment]
I am going to release new package by myself

**Comment by vmarkovtsev** [comment]
Not anymore
