### ISSUE TITLE
Avoid using pandas

### ISSUE THREAD

**Issue by warenlg** [src-d/ml#332]
pandas slows down a lot the installation and is used only once in the repo https://github.com/src-d/ml/blob/master/sourced/ml/cmd/id2role_eval.py#L15 I believe we could avoid using it, and use the `CSVSaver` method instead https://github.com/src-d/ml/blob/master/sourced/ml/transformers/basic.py#L72.

**Comment by zurk** [comment]
yeah, I remember this one. Unfortunately, I use `pandas` more than just CSV loader here. `isin`, `groupby` is not so easy to exclude. But what is definitely can be done is to move `pandas` to `extras_require` as we do with tensorflow.

I can PR it if you want.

**Comment by zurk** [comment]
Is it fixed?
