### ISSUE TITLE
How can I use the ast2vec?

### ISSUE THREAD

**Issue by DennisShaw** [src-d/ml#341]
I want  to embedding AST tree nodes to vector.Would you mind helping me?Thank you

**Comment by vmarkovtsev** [comment]
@DennisShaw There several embedding types depending on how you want to group the nodes. Internal type? Topology? Graph Network to solve a particular problem? etc.

Worth having a look at code2vec, also GGNN papers by Miltos Alamanis.

That being said, this project does not contain any straightforward wrappers or end-user commands for that. Cheers.
