### ISSUE TITLE
Reanimate sourced-ml

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/ml#373]
We need to make CI pass again!

This includes modelforge ^0.11

**Comment by warenlg** [comment]
As regards modelforge porting, I'm working on it here https://github.com/src-d/ml/pull/374

**Comment by warenlg** [comment]
https://github.com/src-d/ml/pull/374 is merged and `sourced-ml` now supports modelforge 0.11.
Next steps would be to switch to `jgit-spark-connector`, `gitbase`, `bblfsh v2` ...etc

**Comment by vmarkovtsev** [comment]
We need @EgorBu to rebase

**Comment by vmarkovtsev** [comment]
Reanimated.
